// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package workflow

// =============================================================
// Top-level workflow
// =============================================================
type WorkflowV1 struct {
	SchemaVersion int64 `json:"schemaVersion"`

	PluginVersion any/* CUE disjunction: (null|string) */ `json:"pluginVersion"`

	FeatureId string `json:"featureId"`

	FeatureName string `json:"featureName"`

	FeatDir string `json:"featDir"`

	OriginalRequest string `json:"originalRequest"`

	Operator OperatorInfo `json:"operator"`

	Config WorkflowConfig `json:"config"`

	StartedAt string `json:"startedAt"`

	UpdatedAt string `json:"updatedAt"`

	CompletedAt any/* CUE disjunction: (null|string) */ `json:"completedAt"`

	TotalElapsedMin any/* CUE number; int64 or float64 */ `json:"totalElapsedMin"`

	CurrentStepId string `json:"currentStepId"`

	NextStepId string `json:"nextStepId"`

	TotalSteps int64 `json:"totalSteps"`

	CompletedSteps int64 `json:"completedSteps"`

	Notes []any/* CUE closed list */ `json:"notes"`

	GlobalWarnings []any/* CUE closed list */ `json:"globalWarnings"`

	Steps []Step `json:"steps"`
}

type OperatorInfo struct {
	Locale string `json:"locale"`
}

type WorkflowConfig struct {
	Mode string `json:"mode"`

	ExecutionStrategy string `json:"executionStrategy,omitempty"`

	TestExecutionDepth string `json:"testExecutionDepth,omitempty"`

	TestExecutionDepthAuto bool `json:"testExecutionDepthAuto,omitempty"`

	SetAt string `json:"setAt"`

	SwitchedFrom string `json:"switchedFrom,omitempty"`

	SwitchedAt string `json:"switchedAt,omitempty"`
}

// =============================================================
// Step base + step-type discriminator
// =============================================================
// #Step is a discriminated union: name selects which payload struct applies.
// Closed disjunction — any name not in the registry is rejected.
type Step map[string]any

type Note struct {
	At string `json:"at"`

	StepId string `json:"stepId,omitempty"`

	Message string `json:"message"`
}

type GlobalWarning struct {
	At string `json:"at"`

	StepId string `json:"stepId,omitempty"`

	Message string `json:"message"`
}

// #StepName lists the canonical step names. The CLI also accepts
// operator-facing aliases (e.g. "TASKS" → "TASKS_MANIFEST", "BRAINSTORM"
// → "BRAINSTORMING") which are intentionally NOT modelled in the CUE
// schema — they are a CLI-UX concern, not a workflow-state concern. The
// alias map lives in `packages/cli/internal/schema/describe.go`
// (`StepTypeAliases` + `ResolveStepAlias`); modifying CUE step names
// here requires updating that map in lockstep so the CLI surface stays
// consistent. Codegen from CUE → Go is intentionally not wired for the
// alias table; the cross-reference comments above and at the Go SSOT
// are the agreed sync mechanism.
type StepName string

type StepStatus string

type StepBase map[string]any /* CUE top */

type StepApplicability struct {
	Applicable bool `json:"applicable"`

	Reason string `json:"reason"`
}

type StepWorktrees struct {
	Used bool `json:"used"`

	Worktrees []any/* CUE closed list */ `json:"worktrees"`
}

type WorktreeEntry struct {
	Name string `json:"name"`

	Status string `json:"status"`
}

type Warning struct {
	Kind string `json:"kind"`

	Message string `json:"message"`

	At string `json:"at,omitempty"`
}

type ReviewExchange struct {
	Round int64 `json:"round"`

	Proposal string `json:"proposal"`

	OperatorAction string `json:"operatorAction"`

	OperatorNote string `json:"operatorNote"`

	DecidedAt string `json:"decidedAt"`
}

type DispatchRecord struct {
	AgentId string `json:"agentId"`

	DispatchPromptDigest string `json:"dispatchPromptDigest"`

	PromptByteCount int64 `json:"promptByteCount"`

	PromptPath string `json:"promptPath"`

	RenderTemplateUsed any/* CUE disjunction: (null|string) */ `json:"renderTemplateUsed"`

	DispatchedAt string `json:"dispatchedAt"`

	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	Status string `json:"status"`

	FindingsAddressed []any/* CUE closed list */ `json:"findingsAddressed"`

	FilesModified []any/* CUE closed list */ `json:"filesModified"`

	FilesCreated []any/* CUE closed list */ `json:"filesCreated"`

	FilesDeleted []any/* CUE closed list */ `json:"filesDeleted"`
}

// =============================================================
// PRD step + payload
// =============================================================
type PRDStep map[string]any /* CUE top */

type PRD struct {
	Title string `json:"title"`

	Overview string `json:"overview"`

	Personas []any/* CUE closed list */ `json:"personas"`

	Objectives []any/* CUE closed list */ `json:"objectives"`

	InScope []any/* CUE closed list */ `json:"inScope"`

	OutOfScope []any/* CUE closed list */ `json:"outOfScope"`

	Deliverables []any/* CUE closed list */ `json:"deliverables"`

	FunctionalRequirements []FR `json:"functionalRequirements"`

	NonFunctionalRequirements []any/* CUE closed list */ `json:"nonFunctionalRequirements"`

	SuccessMetrics []any/* CUE closed list */ `json:"successMetrics"`

	AcceptanceCriteria []AC `json:"acceptanceCriteria"`

	Risks []any/* CUE closed list */ `json:"risks"`

	Dependencies PRDDependencies `json:"dependencies,omitempty"`

	Assumptions []any/* CUE closed list */ `json:"assumptions"`

	TaskGranularity string `json:"taskGranularity"`
}

type FR struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	Priority string `json:"priority,omitempty"`
}

type AC struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	BindsTo []string `json:"bindsTo,omitempty"`
}

type PRDDependencies struct {
	External []string `json:"external,omitempty"`

	Internal []string `json:"internal,omitempty"`
}

type Persona struct {
	Id string `json:"id"`

	Description string `json:"description"`
}

type NFR struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	Category string `json:"category,omitempty"`

	Target string `json:"target"`
}

type SuccessMetric struct {
	Id string `json:"id"`

	Metric string `json:"metric"`

	Target string `json:"target"`

	Method string `json:"method"`
}

type Risk struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	Mitigation string `json:"mitigation"`
}

// =============================================================
// TASKS_MANIFEST
// =============================================================
type TasksManifestStep map[string]any /* CUE top */

type TasksManifest struct {
	TotalTasks int64 `json:"totalTasks"`

	TasksOrder []string `json:"tasksOrder"`

	DependencyGraph map[string][]string `json:"dependencyGraph"`

	Parallelizable []any/* CUE closed list */ `json:"parallelizable"`

	Tasks []TaskBrief `json:"tasks,omitempty"`

	// suppressedRedundantTasks records candidate TASKs the Reviewer pass dropped
	// because their scope is a strict subset of a canonical pipeline phase
	// (write-tests, update-docs, code-review, commit, feature-acceptance,
	// receiving-code-review). Captured for retro auditability — the canonical
	// phase still runs at the end of the pipeline, so duplicating it as a TASK
	// is wasted dispatch. Added 2026-05-07 (RETRO §14 + §17).
	SuppressedRedundantTasks []SuppressedRedundantTask `json:"suppressedRedundantTasks,omitempty"`

	// granularityWarnings records the output of the tertiary granularity-review
	// pass in `generate-task` (R-15 / RETRO §15). Each entry flags a task that
	// is too small (recommend collapse) or too large (recommend split). The
	// operator sees these before `execute-task` runs so the plan can be
	// adjusted without a full re-decomposition cycle. Added 2026-05-07.
	GranularityWarnings []GranularityWarning `json:"granularityWarnings,omitempty"`
}

type TaskBrief struct {
	TaskId string `json:"taskId"`

	Title string `json:"title"`

	SuggestedModel any/* CUE disjunction: (null|string) */ `json:"suggestedModel"`

	Trivial bool `json:"trivial"`

	SkillsFound []any/* CUE closed list */ `json:"skillsFound"`

	Scope []any/* CUE closed list */ `json:"scope"`

	DependsOn []string `json:"dependsOn,omitempty"`
}

// #SuppressedRedundantTask — one entry per candidate TASK dropped by the
// Reviewer-pass canonical-phase filter. `reason` MUST follow the form
// `duplicates-canonical-phase-<phase>` so retros can group by phase.
type SuppressedRedundantTask struct {
	CandidateTitle string `json:"candidateTitle"`

	CandidateScope []string `json:"candidateScope"`

	Reason string `json:"reason"`

	DetectedBy string `json:"detectedBy,omitempty"`
}

// #GranularityWarning — one entry per task flagged by the tertiary
// granularity-review pass in `generate-task` (R-15 / RETRO §15).
// `verdict` is "collapse" when the task has <2 files in scope (recommend
// merging with a sibling), or "split" when it has >10 files (recommend
// decomposing further). `reason` is the free-form prose from the haiku
// granularity reviewer. Added 2026-05-07.
type GranularityWarning struct {
	TaskId string `json:"taskId"`

	Verdict string `json:"verdict"`

	Reason string `json:"reason"`
}

// =============================================================
// TASK step + payload
// =============================================================
type TaskStep map[string]any /* CUE top */

type TaskExecution struct {
	Title string `json:"title,omitempty"`

	Scope []string `json:"scope"`

	DependsOn []string `json:"dependsOn,omitempty"`

	Invariants []any/* CUE closed list */ `json:"invariants"`

	AcceptanceCriteria []TaskAC `json:"acceptanceCriteria,omitempty"`

	SuggestedModel any/* CUE disjunction: (null|string) */ `json:"suggestedModel"`

	Trivial bool `json:"trivial"`

	Explorer TaskExplorer `json:"explorer,omitempty"`

	Reviewer TaskReviewer `json:"reviewer,omitempty"`

	Execution TaskExecutionResult `json:"execution"`
}

type TaskAC struct {
	Id string `json:"id"`

	BindsTo []string `json:"bindsTo"`

	Description string `json:"description,omitempty"`
}

type TaskExplorer struct {
	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	CompletedAt string `json:"completedAt,omitempty"`

	FilesModified []any/* CUE closed list */ `json:"filesModified"`

	FilesToRead []any/* CUE closed list */ `json:"filesToRead"`

	DepsGraph map[string]struct {
		Imports []string `json:"imports,omitempty"`

		ImportedBy []string `json:"importedBy,omitempty"`
	} `json:"depsGraph,omitempty"`

	Domains []any/* CUE closed list */ `json:"domains"`

	SkillsFound []any/* CUE closed list */ `json:"skillsFound"`
}

type TaskReviewer struct {
	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	CompletedAt string `json:"completedAt,omitempty"`

	// additionalContext: free-form prose (default "") OR a structured object
	// consumable by the `reapply-additional-context` mutator (apply.go:1011).
	// String form is preserved for back-compat and skill orchestrators that
	// emit prose summaries; object form is the canonical shape consumed by
	// the mutator to translate Reviewer corrections into `task.scope` updates.
	AdditionalContext any/* CUE disjunction: (string|struct) */ `json:"additionalContext"`

	SkipTestsReason any/* CUE disjunction: (null|string) */ `json:"skipTestsReason"`

	TestSpecs []any/* CUE closed list */ `json:"testSpecs"`
}

type TaskExecutionResult struct {
	Gates TaskGates `json:"gates"`

	Files TaskFiles `json:"files,omitempty"`

	FilesModified []string `json:"filesModified,omitempty"`

	FilesCreated []string `json:"filesCreated,omitempty"`

	FilesDeleted []string `json:"filesDeleted,omitempty"`

	ScopeAdjustments []any/* CUE closed list */ `json:"scopeAdjustments"`

	Agents []any/* CUE closed list */ `json:"agents"`

	InvariantsChecked []any/* CUE closed list */ `json:"invariantsChecked"`

	FileEditsSummary map[string]struct {
		Edits int64 `json:"edits,omitempty"`

		Details []string `json:"details,omitempty"`
	} `json:"fileEditsSummary,omitempty"`

	TestsRan TestsRan `json:"testsRan,omitempty"`

	NextSteps string `json:"nextSteps"`
}

type TaskGates struct {
	Baseline GateRow `json:"baseline"`

	PostChange GateRow `json:"postChange"`

	Regression []any/* CUE closed list */ `json:"regression"`
}

type GateRow map[string]any /* CUE top */

type TaskFiles struct {
	Created []any/* CUE closed list */ `json:"created"`

	Modified []any/* CUE closed list */ `json:"modified"`

	Deleted []any/* CUE closed list */ `json:"deleted"`
}

type TestsRan struct {
	PreChange struct {
		TestCount string `json:"testCount,omitempty"`

		Duration string `json:"duration,omitempty"`

		Details string `json:"details,omitempty"`
	} `json:"preChange,omitempty"`

	PostChange struct {
		TestCount string `json:"testCount,omitempty"`

		Duration string `json:"duration,omitempty"`

		Details string `json:"details,omitempty"`
	} `json:"postChange,omitempty"`
}

type Invariant struct {
	Rule string `json:"rule"`

	Source string `json:"source,omitempty"`
}

type SkillFound struct {
	Domain string `json:"domain"`

	Skill string `json:"skill"`

	Relevance string `json:"relevance"`
}

// #AdditionalContextObj is the structured shape consumed by the
// `browzer workflow reapply-additional-context` mutator (apply.go:1011).
// Each #FileChange entry rewrites task.scope per its `kind`:
//   - corrected: replaces `from` with `to`
//   - added:     appends `path` (or `to` as fallback) to scope
//   - dropped:   removes `path` (or `from` as fallback) from scope
//
// Schema added 2026-05-04 (WF-SYNC-2): mutator already implemented this
// shape since 2026-04-24; the schema previously declared `string` only,
// causing CUE rejection of the legitimate runtime contract.
type AdditionalContextObj struct {
	Changes []FileChange `json:"changes"`
}

// #FileChange entries rewrite TASK fields per `kind`:
//   - corrected:     replaces `from` path with `to` path inside task.scope
//   - added:         appends `path` (or `to` as fallback) to task.scope
//   - dropped:       removes `path` (or `from` as fallback) from task.scope
//   - rename-domain: rewrites `from` → `to` inside task.explorer.domains AND
//     propagates the rename to task.explorer.skillsFound[].domain.
//     Closes RETRO PR 6 §5.6 — previously, fixing a typo in a
//     domain string required out-of-band jq surgery on the
//     /tmp/reviewer-tasks.json file before append-steps.
type FileChange struct {
	Kind string `json:"kind"`

	From string `json:"from,omitempty"`

	To string `json:"to,omitempty"`

	Path string `json:"path,omitempty"`

	Reason string `json:"reason,omitempty"`
}

// #TestSpec — Reviewer-emitted green-test plan entry. RETRO PR 6 §2.3 (2026-05-06):
//   - `type` (literal "green") was renamed to `intent` (the semantic axis: which
//     stage of the red→green→refactor loop the spec satisfies). Adding an enum
//     for `intent` clarifies that other plan stages exist; for now only "green"
//     is emitted by `generate-task` — `red` and `chaos` are reserved for future
//     reviewer passes that emit failing-first or fault-injection specs.
//   - `scope` is a NEW required field naming the testing layer the spec belongs
//     to. Replaces the cargo-culted `type: "unit"|"integration"|"e2e"` LLMs kept
//     emitting because the universal testing convention overloads the word
//     `type`. `scope` resolves the collision and is mandatory for the
//     `write-tests` skill's per-runner dispatch logic.
//
// CONTRACT BREAK: no `type:"green"` back-compat alias — schema v2 was already a
// hard cutoff per WORKFLOW_SYNC_REDESIGN.md §5; consumers must move to `intent`
// + `scope`.
type TestSpec struct {
	TestId string `json:"testId"`

	File string `json:"file"`

	Intent string `json:"intent"`

	Scope string `json:"scope"`

	Description string `json:"description"`

	CoverageTarget string `json:"coverageTarget,omitempty"`
}

type RegressionRow struct {
	File string `json:"file"`

	Test string `json:"test"`

	Result string `json:"result"`
}

type TaskAgent struct {
	Role string `json:"role"`

	Skill string `json:"skill"`

	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	Status string `json:"status"`

	StartedAt string `json:"startedAt,omitempty"`

	CompletedAt string `json:"completedAt,omitempty"`

	SkillsLoaded []string `json:"skillsLoaded,omitempty"`

	// First-class per-agent file ledger (TE2-T3.2, 2026-05-08). Closes
	// the cargo-culted `files=<created>/<modified>` cursor convention by
	// surfacing structured paths the orchestrator + code-review skill can
	// read without re-discovering via diff. Mirrors the pre-existing
	// shape on #DispatchRecord. Optional + default `[]` so existing
	// workflow.json fixtures stay valid under v2.
	FilesCreated []any/* CUE closed list */ `json:"filesCreated"`

	FilesModified []any/* CUE closed list */ `json:"filesModified"`

	Notes string `json:"notes,omitempty"`
}

type InvariantCheck struct {
	Rule string `json:"rule"`

	Source string `json:"source"`

	Status string `json:"status"`

	Note string `json:"note,omitempty"`
}

type ScopeAdjustment struct {
	Kind string `json:"kind"`

	Adjustment string `json:"adjustment"`

	Reason string `json:"reason"`

	Resolution string `json:"resolution"`

	Owner string `json:"owner"`

	LoggedAsWarning bool `json:"loggedAsWarning,omitempty"`
}

// =============================================================
// BRAINSTORMING
// =============================================================
type BrainstormingStep map[string]any /* CUE top */

type Brainstorming struct {
	QuestionsAsked int64 `json:"questionsAsked"`

	ResearchRoundRun bool `json:"researchRoundRun"`

	ResearchAgents int64 `json:"researchAgents"`

	Dimensions BrainstormDimensions `json:"dimensions"`

	ResearchFindings []any/* CUE closed list */ `json:"researchFindings"`

	Assumptions []any/* CUE closed list */ `json:"assumptions"`

	OpenRisks []any/* CUE closed list */ `json:"openRisks"`

	Decision any/* CUE disjunction: (null|struct) */ `json:"decision"`
}

type BrainstormDimensions struct {
	PrimaryUser string `json:"primaryUser"`

	JobToBeDone string `json:"jobToBeDone"`

	SuccessSignal string `json:"successSignal"`

	InScope []string `json:"inScope"`

	OutOfScope []string `json:"outOfScope"`

	RepoSurface []any/* CUE closed list */ `json:"repoSurface"`

	TechConstraints []any/* CUE closed list */ `json:"techConstraints"`

	FailureModes []any/* CUE closed list */ `json:"failureModes"`

	AcceptanceCriteria []any/* CUE closed list */ `json:"acceptanceCriteria"`

	Dependencies []any/* CUE closed list */ `json:"dependencies"`

	OpenQuestions []any/* CUE closed list */ `json:"openQuestions"`
}

type BrainstormDecision struct {
	Chosen string `json:"chosen"`

	Rationale string `json:"rationale"`

	AlternativesConsidered []any/* CUE closed list */ `json:"alternativesConsidered"`
}

type BrainstormAlternative struct {
	Name string `json:"name"`

	Reason_rejected string `json:"reason-rejected"`
}

type ResearchFinding struct {
	Question string `json:"question"`

	Answer string `json:"answer"`

	Confidence string `json:"confidence"`

	Sources []any/* CUE closed list */ `json:"sources"`
}

// =============================================================
// CODE_REVIEW
// =============================================================
type CodeReviewStep map[string]any /* CUE top */

type CodeReview struct {
	AgentTeamsEnabled bool `json:"agentTeamsEnabled,omitempty"`

	DispatchMode string `json:"dispatchMode"`

	ReviewTier string `json:"reviewTier"`

	TokenCostEstimate int64 `json:"tokenCostEstimate,omitempty"`

	MandatoryMembers []string `json:"mandatoryMembers"`

	RecommendedMembers []any/* CUE closed list */ `json:"recommendedMembers"`

	CustomMembers []any/* CUE closed list */ `json:"customMembers"`

	Consolidator CodeReviewConsolidator `json:"consolidator,omitempty"`

	Baseline CodeReviewBaseline `json:"baseline,omitempty"`

	SeverityCounts SeverityCounts `json:"severityCounts,omitempty"`

	CyclomaticAudit CyclomaticAudit `json:"cyclomaticAudit,omitempty"`

	DuplicationFindings []any/* CUE closed list */ `json:"duplicationFindings"`

	RegressionRun any/* CUE disjunction: (null|struct) */ `json:"regressionRun"`

	Findings []any/* CUE closed list */ `json:"findings"`

	// True when the operator pre-registered dispatchMode + reviewTier in
	// `Skill(code-review, "dispatchMode: <…>; tier: <…>")` under autonomous
	// mode, bypassing the Phase-1 prompt. See code-review/SKILL.md §1.
	PreRegistered bool `json:"preRegistered"`

	// Optional gate verdict for the consolidated review. When set, drives
	// automated merge/block logic in receiving-code-review skill.
	// "advisory-only" never blocks; "fail-on-high" blocks on severity=high;
	// "fail-on-medium-or-high" blocks on medium or high.
	Gate any/* CUE disjunction: (null|string) */ `json:"gate,omitempty"`

	// Exit code of the consolidated gate check. null = not yet run.
	ExitCode any/* CUE disjunction: (null|int) */ `json:"exitCode,omitempty"`

	// Sensitive-path scan result from the FR-3 gate (populated by code-review
	// skill when it detects files matching references/sensitive-paths.md).
	SensitivePathGate any/* CUE disjunction: (null|struct) */ `json:"sensitivePathGate,omitempty"`
}

type CodeReviewConsolidator struct {
	Mode string `json:"mode"`

	Reason string `json:"reason,omitempty"`
}

type CodeReviewBaseline struct {
	Source string `json:"source"`

	ReusedGates []any/* CUE closed list */ `json:"reusedGates"`

	FreshGates []any/* CUE closed list */ `json:"freshGates"`

	Duration string `json:"duration,omitempty"`

	// The literal lint+typecheck+test command run for the baseline gate,
	// persisted verbatim for the audit log. See code-review/SKILL.md §1.
	Command string `json:"command"`

	// Enumerated per-test failures parsed from the baseline run.
	// Lumped counts (`failureCount: N` without an array) are rejected by
	// the skill's failure-enumeration contract — see code-review/SKILL.md
	// §1 + references/regression-tester.md §Pre-existing-on-main.
	Failures []any/* CUE closed list */ `json:"failures"`
}

type SeverityCounts struct {
	High int64 `json:"high"`

	Medium int64 `json:"medium"`

	Low int64 `json:"low"`
}

type CyclomaticAudit struct {
	ConductedBy string `json:"conductedBy"`

	Files []any/* CUE closed list */ `json:"files"`
}

type SensitivePathGate struct {
	Matched bool `json:"matched"`

	MatchedFiles []string `json:"matchedFiles"`
}

type CyclomaticFile struct {
	File string `json:"file"`

	MaxComplexity int64 `json:"maxComplexity"`

	Threshold int64 `json:"threshold"`

	Verdict string `json:"verdict"`
}

type DuplicationFinding struct {
	Pattern string `json:"pattern"`

	Files []string `json:"files"`

	SuggestedExtraction string `json:"suggestedExtraction"`
}

type RegressionRun struct {
	Tool string `json:"tool"`

	Scope string `json:"scope"`

	Command string `json:"command"`

	CommandSource string `json:"commandSource"`

	ExecutionDepth string `json:"executionDepth"`

	FilesInRadius int64 `json:"filesInRadius"`

	TestFilesExecuted int64 `json:"testFilesExecuted"`

	ExitCode int64 `json:"exitCode"`

	Passed int64 `json:"passed"`

	Failed int64 `json:"failed"`

	SkippedTests int64 `json:"skippedTests"`

	Duration string `json:"duration,omitempty"`

	Skipped bool `json:"skipped"`

	SkipReason any/* CUE disjunction: (null|string) */ `json:"skipReason"`

	Summary string `json:"summary"`

	Failures []any/* CUE closed list */ `json:"failures"`
}

type RegressionFailure struct {
	TestFile string `json:"testFile"`

	TestName string `json:"testName"`

	Error string `json:"error"`
}

// #Finding.id — global finding identifier assigned by `browzer codereview aggregate`.
//
// # Pattern
//
// The pattern =~"^F-[0-9]+$" deliberately accepts BOTH forms:
//   - Legacy (schema v1/v2, pre-2026-05-12): "F-1", "F-2", … (no zero-padding)
//   - Canonical (post-aggregate output): "F-001", "F-002", … (zero-padded to 3 digits)
//
// DO NOT tighten this to ^F-[0-9]{3}$ — that would break existing workflow.json
// files produced by earlier CLI versions (NFR-2 retrocompat).
//
// # Convention
//
// The aggregator (internal/codereview/aggregate.go) ALWAYS emits zero-padded
// F-NNN ids for newly produced consolidated CODE_REVIEW.json files.  Consumers
// should treat F-NNN as the canonical form going forward.
//
// # mergedFrom[] IDs
//
// The sibling mergedFrom[] array uses per-member prefixes (e.g. "SR-3", "QA-1").
// Its separate pattern =~"^[A-Z]{2,6}-[0-9]+$" does NOT require zero-padding
// because per-member ids use the unpadded form by design.
type Finding struct {
	Id string `json:"id"`

	Domain string `json:"domain"`

	Severity string `json:"severity"`

	Category string `json:"category"`

	File string `json:"file"`

	Line int64 `json:"line,omitempty"`

	Description string `json:"description"`

	SuggestedFix string `json:"suggestedFix"`

	AssignedSkill any/* CUE disjunction: (null|string) */ `json:"assignedSkill"`

	Status string `json:"status"`

	// Set to true when the same finding was raised by an off-lane reviewer
	// (cross-domain duplicate). The off-lane copies become advisory and the
	// owning lane drives the fix. See code-review/references/severity-matrix.md §49.
	CrossLaneOverlap bool `json:"crossLaneOverlap"`

	// IDs of sibling findings that were merged into this one during
	// consolidation (format: "<lane>-<seq>", e.g. "SR-3", "QA-1").
	MergedFrom []string `json:"mergedFrom,omitempty"`
}

// =============================================================
// RECEIVING_CODE_REVIEW
// =============================================================
type ReceivingCodeReviewStep map[string]any /* CUE top */

type ReceivingCodeReview struct {
	Iteration int64 `json:"iteration"`

	Summary ReceivingSummary `json:"summary"`

	Dispatches []any/* CUE closed list */ `json:"dispatches"`

	Unrecovered []any/* CUE closed list */ `json:"unrecovered"`

	Notes string `json:"notes"`
}

type ReceivingSummary struct {
	Total int64 `json:"total"`

	Fixed int64 `json:"fixed"`

	Unrecovered int64 `json:"unrecovered"`
}

type ReceivingDispatch struct {
	FindingId string `json:"findingId"`

	Iteration int64 `json:"iteration"`

	Reason string `json:"reason"`

	Role string `json:"role"`

	Skill string `json:"skill"`

	Model string `json:"model"`

	Status string `json:"status"`

	FilesChanged []any/* CUE closed list */ `json:"filesChanged"`

	GatesPostFix struct {
		Lint string `json:"lint,omitempty"`

		Typecheck string `json:"typecheck,omitempty"`

		Tests string `json:"tests,omitempty"`
	} `json:"gatesPostFix,omitempty"`

	ResearchBundle any/* CUE disjunction: (null|string) */ `json:"researchBundle"`

	FailureTrace any/* CUE disjunction: (null|string) */ `json:"failureTrace"`

	StartedAt string `json:"startedAt"`

	CompletedAt string `json:"completedAt"`
}

type UnrecoveredFinding struct {
	FindingId string `json:"findingId"`

	Severity string `json:"severity"`

	LastTrace string `json:"lastTrace"`

	TotalIterations int64 `json:"totalIterations"`

	ModelsTried []string `json:"modelsTried"`

	ResearchPassesRun int64 `json:"researchPassesRun"`

	LoggedToTechDebt any/* CUE disjunction: (null|string) */ `json:"loggedToTechDebt"`
}

// =============================================================
// WRITE_TESTS
// =============================================================
type WriteTestsStep map[string]any /* CUE top */

type WriteTests struct {
	Skipped bool `json:"skipped"`

	SkipReason any/* CUE disjunction: (null|string) */ `json:"skipReason"`

	Runner any/* CUE disjunction: (null|string) */ `json:"runner"`

	FilesAuthored []any/* CUE closed list */ `json:"filesAuthored"`

	GreenTests GreenTests `json:"greenTests,omitempty"`

	MutationTesting MutationTesting `json:"mutationTesting,omitempty"`

	Notes string `json:"notes"`

	// Flat top-level aliases for mutation results (additive, backward-compat).
	// Both the nested mutationTesting.{score,…} and these flat fields are
	// accepted; tools may populate either or both. Added 2026-05-11.
	MutationScore any/* CUE disjunction: (null|int) */ `json:"mutationScore,omitempty"`

	Killed any/* CUE disjunction: (null|int) */ `json:"killed,omitempty"`

	Survived any/* CUE disjunction: (null|int) */ `json:"survived,omitempty"`

	Categories any/* CUE disjunction: (null|list) */ `json:"categories,omitempty"`
}

type GreenTests struct {
	Added int64 `json:"added"`

	Augmented int64 `json:"augmented"`

	Duration string `json:"duration,omitempty"`
}

type MutationTesting struct {
	Ran bool `json:"ran"`

	Tool any/* CUE disjunction: (null|string) */ `json:"tool"`

	Score int64 `json:"score"`

	Target int64 `json:"target"`

	Survivors []any/* CUE closed list */ `json:"survivors"`

	CoverageGap any/* CUE disjunction: (null|struct) */ `json:"coverageGap"`
}

type MutationSurvivor struct {
	File string `json:"file"`

	Line int64 `json:"line"`

	Mutator string `json:"mutator"`

	KilledByNewTest bool `json:"killedByNewTest"`

	AddedTestFile string `json:"addedTestFile"`
}

type MutationCoverageGap struct {
	Reason string `json:"reason"`

	UncoveredFiles []string `json:"uncoveredFiles"`

	Remediation string `json:"remediation"`
}

// =============================================================
// UPDATE_DOCS
// =============================================================
type UpdateDocsStep map[string]any /* CUE top */

type UpdateDocs struct {
	DocsMentioning []any/* CUE closed list */ `json:"docsMentioning"`

	AnchorDocsAlwaysIncluded []any/* CUE closed list */ `json:"anchorDocsAlwaysIncluded"`

	Patches []any/* CUE closed list */ `json:"patches"`

	TwoPassRun TwoPassRun `json:"twoPassRun"`

	// signals records the browzer-mentions / browzer-deps scan signals that
	// drove Phase A discovery. Each entry names the signal, its source command,
	// whether it returned results (hit), and an optional result count.
	Signals any/* CUE disjunction: (null|list) */ `json:"signals,omitempty"`

	// enoentScan records whether Phase B ran a missing-file sweep and which
	// files (if any) were absent from the filesystem at patch time.
	EnoentScan any/* CUE disjunction: (null|struct) */ `json:"enoentScan,omitempty"`
}

type TwoPassRun struct {
	DirectRef bool `json:"directRef"`

	ConceptLevel bool `json:"conceptLevel"`

	MentionsPass bool `json:"mentionsPass"`

	MentionsFallbackUsed bool `json:"mentionsFallbackUsed"`

	// REMOVED 2026-05-05 (B8): legacy `mentionsFallback: *null | string`. No active
	// consumer; superseded by `mentionsFallbackUsed` (boolean). Migration:
	//
	//	jq 'del(.steps[].updateDocs.twoPassRun.mentionsFallback)' workflow.json
	MentionsResultEmpty any/* CUE disjunction: (null|string) */ `json:"mentionsResultEmpty"`
}

type UpdateDocsSignal struct {
	Name string `json:"name"`

	Source string `json:"source"`

	Hit bool `json:"hit"`

	Count int64 `json:"count,omitempty"`
}

type UpdateDocsEnoentScan struct {
	Ran bool `json:"ran"`

	MissingFiles []string `json:"missingFiles"`
}

type DocMention struct {
	SourceFile string `json:"sourceFile"`

	MentionedBy []struct {
		Doc string `json:"doc"`

		Confidence float64 `json:"confidence"`
	} `json:"mentionedBy"`
}

type AnchorDoc struct {
	Doc string `json:"doc"`

	Source string `json:"source"`

	Disposition string `json:"disposition"`
}

type DocPatch struct {
	Doc string `json:"doc"`

	Reason string `json:"reason"`

	LinesChanged int64 `json:"linesChanged"`

	Verdict string `json:"verdict"`

	Notes string `json:"notes,omitempty"`
}

// =============================================================
// FEATURE_ACCEPTANCE
// =============================================================
type FeatureAcceptanceStep map[string]any /* CUE top */

type FeatureAcceptance struct {
	// mode is now optional (not required) to allow partial/in-progress saves.
	// Enum extended to include "autonomous-with-stack-boot" (2026-05-11).
	Mode string `json:"mode,omitempty"`

	ModeNote string `json:"modeNote,omitempty"`

	AcceptanceCriteria []FAcceptanceCriterion `json:"acceptanceCriteria"`

	NfrVerifications []any/* CUE closed list */ `json:"nfrVerifications"`

	SuccessMetrics []any/* CUE closed list */ `json:"successMetrics"`

	AcRelaxations []any/* CUE closed list */ `json:"acRelaxations"`

	OperatorActionsRequested []any/* CUE closed list */ `json:"operatorActionsRequested"`

	Verdict string `json:"verdict,omitempty"`

	ExecutionRequiredProbe bool `json:"executionRequiredProbe"`

	LiveVerificationAttempt bool `json:"liveVerificationAttempt"`

	// True when the operator pre-registered `mode: <…>` in
	// `Skill(feature-acceptance, "mode: <autonomous|manual|hybrid>; …")`,
	// bypassing the Phase-1 prompt. See feature-acceptance/SKILL.md §1.
	PreRegistered bool `json:"preRegistered"`
}

type FAcceptanceCriterion struct {
	Id string `json:"id"`

	Status string `json:"status"`

	Evidence string `json:"evidence"`

	Method string `json:"method"`

	Rationale string `json:"rationale,omitempty"`
}

type FNFR struct {
	Id string `json:"id"`

	Status string `json:"status"`

	CoversAcceptanceSignal string `json:"coversAcceptanceSignal"`

	Evidence string `json:"evidence"`

	Measured string `json:"measured"`

	Target string `json:"target"`
}

type FSuccessMetric struct {
	Id string `json:"id"`

	Measured any/* CUE disjunction: (string|number) */ `json:"measured"`

	Target any/* CUE disjunction: (string|number) */ `json:"target"`

	Status string `json:"status"`

	// Live-verification gate result. The §2.5 step in feature-acceptance
	// flips `resolved: true` only after the live probe agrees with `status`,
	// and records the `rationale` (reason / evidence pointer) so a later
	// audit can re-verify the decision. See feature-acceptance/references/
	// live-verify.md.
	Resolved bool `json:"resolved"`

	Rationale string `json:"rationale"`
}

type ACRelaxation struct {
	AcId string `json:"acId"`

	OriginalTarget string `json:"originalTarget"`

	RelaxedTarget string `json:"relaxedTarget"`

	Rationale string `json:"rationale"`

	Source string `json:"source"`

	At string `json:"at"`
}

type OperatorAction struct {
	Ac any/* CUE disjunction: (null|string) */ `json:"ac"`

	Kind string `json:"kind"`

	Description string `json:"description"`

	At string `json:"at"`

	Resolved bool `json:"resolved"`

	Resolution any/* CUE disjunction: (null|string) */ `json:"resolution"`
}

// =============================================================
// COMMIT
// =============================================================
type CommitStep map[string]any /* CUE top */

type CommitDescriptor struct {
	Sha string `json:"sha,omitempty"`

	BackfillSha any/* CUE disjunction: (null|string) */ `json:"backfillSha"`

	ConventionalType string `json:"conventionalType"`

	Scope string `json:"scope"`

	Subject string `json:"subject"`

	Body string `json:"body"`

	Trailers []any/* CUE closed list */ `json:"trailers"`

	PrePushAuditsRun []any/* CUE closed list */ `json:"prePushAuditsRun"`

	PushAttempts []any/* CUE closed list */ `json:"pushAttempts"`

	PrePushAudits []any/* CUE closed list */ `json:"prePushAudits"`
}

type PushAttempt struct {
	Sha string `json:"sha"`

	AttemptedAt string `json:"attemptedAt"`

	LefthookBypassed bool `json:"lefthookBypassed"`

	NoVerifyPassed bool `json:"noVerifyPassed"`

	AmendUsed bool `json:"amendUsed"`

	BypassedAudits []any/* CUE closed list */ `json:"bypassedAudits"`

	BypassReason any/* CUE disjunction: (null|string) */ `json:"bypassReason"`

	RetryCount int64 `json:"retryCount"`

	PreviousFailure any/* CUE disjunction: (null|string) */ `json:"previousFailure"`
}

type PrePushAudit struct {
	Name string `json:"name"`

	Source string `json:"source"`

	ExitCode int64 `json:"exitCode"`

	DurationMs int64 `json:"durationMs"`

	Output string `json:"output,omitempty"`
}

// =============================================================
// #StepView — JSON shape returned by `browzer get-step <PHASE> --json`.
// Consolidated, LLM-context-friendly projection of a single step.
// Only `stepId`, `phase`, and `status` are required; everything else is
// optional and depends on the phase.
// =============================================================
type StepView struct {
	StepId string `json:"stepId"`

	Phase string `json:"phase"`

	Status StepStatus `json:"status"`

	Role string `json:"role,omitempty"`

	SkillsToInvoke []string `json:"skillsToInvoke,omitempty"`

	Scope map[string]any/* CUE top */ `json:"scope,omitempty"`

	PrdContext map[string]any/* CUE top */ `json:"prdContext,omitempty"`

	Deps map[string]any/* CUE top */ `json:"deps,omitempty"`

	Invariants []string `json:"invariants,omitempty"`

	DoneWhen []string `json:"doneWhen,omitempty"`

	Body map[string]any/* CUE top */ `json:"body,omitempty"`

	Tasks []map[string]any/* CUE top */ `json:"tasks,omitempty"`

	OriginalRequest string `json:"originalRequest,omitempty"`

	BrainstormSummary string `json:"brainstormSummary,omitempty"`
}

// =============================================================
// Step-type discriminator registry — used by codegen + describe-step-type.
// =============================================================
type StepDefinitions struct {
	PRD PRDStep `json:"PRD"`

	TASKS_MANIFEST TasksManifestStep `json:"TASKS_MANIFEST"`

	TASK TaskStep `json:"TASK"`

	BRAINSTORMING BrainstormingStep `json:"BRAINSTORMING"`

	CODE_REVIEW CodeReviewStep `json:"CODE_REVIEW"`

	RECEIVING_CODE_REVIEW ReceivingCodeReviewStep `json:"RECEIVING_CODE_REVIEW"`

	WRITE_TESTS WriteTestsStep `json:"WRITE_TESTS"`

	UPDATE_DOCS UpdateDocsStep `json:"UPDATE_DOCS"`

	FEATURE_ACCEPTANCE FeatureAcceptanceStep `json:"FEATURE_ACCEPTANCE"`

	COMMIT CommitStep `json:"COMMIT"`
}
