// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package workflow

// =============================================================
// Top-level workflow
// =============================================================
type WorkflowV1 struct {
	SchemaVersion int64 `json:"schemaVersion"`

	PluginVersion any/* CUE disjunction: (null|string) */ `json:"pluginVersion"`

	FeatureId string `json:"featureId"`

	FeatureName string `json:"featureName"`

	FeatDir string `json:"featDir"`

	OriginalRequest string `json:"originalRequest"`

	Operator OperatorInfo `json:"operator"`

	Config WorkflowConfig `json:"config"`

	StartedAt string `json:"startedAt"`

	UpdatedAt string `json:"updatedAt"`

	CompletedAt any/* CUE disjunction: (null|string) */ `json:"completedAt"`

	TotalElapsedMin any/* CUE number; int64 or float64 */ `json:"totalElapsedMin"`

	CurrentStepId string `json:"currentStepId"`

	NextStepId string `json:"nextStepId"`

	TotalSteps int64 `json:"totalSteps"`

	CompletedSteps int64 `json:"completedSteps"`

	Notes []any/* CUE closed list */ `json:"notes"`

	GlobalWarnings []any/* CUE closed list */ `json:"globalWarnings"`

	Steps []Step `json:"steps"`
}

type OperatorInfo struct {
	Locale string `json:"locale"`
}

type WorkflowConfig struct {
	Mode string `json:"mode"`

	ExecutionStrategy string `json:"executionStrategy,omitempty"`

	TestExecutionDepth string `json:"testExecutionDepth,omitempty"`

	TestExecutionDepthAuto bool `json:"testExecutionDepthAuto,omitempty"`

	SetAt string `json:"setAt"`

	SwitchedFrom string `json:"switchedFrom,omitempty"`

	SwitchedAt string `json:"switchedAt,omitempty"`
}

// =============================================================
// Step base + step-type discriminator
// =============================================================
// #Step is a discriminated union: name selects which payload struct applies.
// Closed disjunction — any name not in the registry is rejected.
type Step map[string]any

type Note struct {
	At string `json:"at"`

	StepId string `json:"stepId,omitempty"`

	Message string `json:"message"`
}

type GlobalWarning struct {
	At string `json:"at"`

	StepId string `json:"stepId,omitempty"`

	Message string `json:"message"`
}

type StepName string

type StepStatus string

type StepBase map[string]any /* CUE top */

type StepApplicability struct {
	Applicable bool `json:"applicable"`

	Reason string `json:"reason"`
}

type StepWorktrees struct {
	Used bool `json:"used"`

	Worktrees []any/* CUE closed list */ `json:"worktrees"`
}

type WorktreeEntry struct {
	Name string `json:"name"`

	Status string `json:"status"`
}

type Warning struct {
	Kind string `json:"kind"`

	Message string `json:"message"`

	At string `json:"at,omitempty"`
}

type ReviewExchange struct {
	Round int64 `json:"round"`

	Proposal string `json:"proposal"`

	OperatorAction string `json:"operatorAction"`

	OperatorNote string `json:"operatorNote"`

	DecidedAt string `json:"decidedAt"`
}

type DispatchRecord struct {
	AgentId string `json:"agentId"`

	DispatchPromptDigest string `json:"dispatchPromptDigest"`

	PromptByteCount int64 `json:"promptByteCount"`

	PromptPath string `json:"promptPath"`

	RenderTemplateUsed any/* CUE disjunction: (null|string) */ `json:"renderTemplateUsed"`

	DispatchedAt string `json:"dispatchedAt"`

	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	Status string `json:"status"`

	FindingsAddressed []any/* CUE closed list */ `json:"findingsAddressed"`

	FilesModified []any/* CUE closed list */ `json:"filesModified"`

	FilesCreated []any/* CUE closed list */ `json:"filesCreated"`

	FilesDeleted []any/* CUE closed list */ `json:"filesDeleted"`
}

// =============================================================
// PRD step + payload
// =============================================================
type PRDStep map[string]any /* CUE top */

type PRD struct {
	Title string `json:"title"`

	Overview string `json:"overview"`

	Personas []any/* CUE closed list */ `json:"personas"`

	Objectives []any/* CUE closed list */ `json:"objectives"`

	InScope []any/* CUE closed list */ `json:"inScope"`

	OutOfScope []any/* CUE closed list */ `json:"outOfScope"`

	Deliverables []any/* CUE closed list */ `json:"deliverables"`

	FunctionalRequirements []FR `json:"functionalRequirements"`

	NonFunctionalRequirements []any/* CUE closed list */ `json:"nonFunctionalRequirements"`

	SuccessMetrics []any/* CUE closed list */ `json:"successMetrics"`

	AcceptanceCriteria []AC `json:"acceptanceCriteria"`

	Risks []any/* CUE closed list */ `json:"risks"`

	Dependencies PRDDependencies `json:"dependencies,omitempty"`

	Assumptions []any/* CUE closed list */ `json:"assumptions"`

	TaskGranularity string `json:"taskGranularity"`
}

type FR struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	Priority string `json:"priority,omitempty"`
}

type AC struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	BindsTo []string `json:"bindsTo,omitempty"`
}

type PRDDependencies struct {
	External []string `json:"external,omitempty"`

	Internal []string `json:"internal,omitempty"`
}

type Persona struct {
	Id string `json:"id"`

	Description string `json:"description"`
}

type NFR struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	Category string `json:"category,omitempty"`

	Target string `json:"target"`
}

type SuccessMetric struct {
	Id string `json:"id"`

	Metric string `json:"metric"`

	Target string `json:"target"`

	Method string `json:"method"`
}

type Risk struct {
	Id string `json:"id"`

	Text string `json:"text,omitempty"`

	Description string `json:"description,omitempty"`

	Mitigation string `json:"mitigation"`
}

// =============================================================
// TASKS_MANIFEST
// =============================================================
type TasksManifestStep map[string]any /* CUE top */

type TasksManifest struct {
	TotalTasks int64 `json:"totalTasks"`

	TasksOrder []string `json:"tasksOrder"`

	DependencyGraph map[string][]string `json:"dependencyGraph"`

	Parallelizable []any/* CUE closed list */ `json:"parallelizable"`

	Tasks []TaskBrief `json:"tasks,omitempty"`
}

type TaskBrief struct {
	TaskId string `json:"taskId"`

	Title string `json:"title"`

	SuggestedModel any/* CUE disjunction: (null|string) */ `json:"suggestedModel"`

	Trivial bool `json:"trivial"`

	SkillsFound []any/* CUE closed list */ `json:"skillsFound"`

	Scope []any/* CUE closed list */ `json:"scope"`

	DependsOn []string `json:"dependsOn,omitempty"`
}

// =============================================================
// TASK step + payload
// =============================================================
type TaskStep map[string]any /* CUE top */

type TaskExecution struct {
	Title string `json:"title,omitempty"`

	Scope []string `json:"scope"`

	DependsOn []string `json:"dependsOn,omitempty"`

	Invariants []any/* CUE closed list */ `json:"invariants"`

	AcceptanceCriteria []TaskAC `json:"acceptanceCriteria,omitempty"`

	SuggestedModel any/* CUE disjunction: (null|string) */ `json:"suggestedModel"`

	Trivial bool `json:"trivial"`

	Explorer TaskExplorer `json:"explorer,omitempty"`

	Reviewer TaskReviewer `json:"reviewer,omitempty"`

	Execution TaskExecutionResult `json:"execution"`
}

type TaskAC struct {
	Id string `json:"id"`

	BindsTo []string `json:"bindsTo"`

	Description string `json:"description,omitempty"`
}

type TaskExplorer struct {
	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	CompletedAt string `json:"completedAt,omitempty"`

	FilesModified []any/* CUE closed list */ `json:"filesModified"`

	FilesToRead []any/* CUE closed list */ `json:"filesToRead"`

	DepsGraph map[string]struct {
		Imports []string `json:"imports,omitempty"`

		ImportedBy []string `json:"importedBy,omitempty"`
	} `json:"depsGraph,omitempty"`

	Domains []any/* CUE closed list */ `json:"domains"`

	SkillsFound []any/* CUE closed list */ `json:"skillsFound"`
}

type TaskReviewer struct {
	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	CompletedAt string `json:"completedAt,omitempty"`

	AdditionalContext string `json:"additionalContext"`

	SkipTestsReason any/* CUE disjunction: (null|string) */ `json:"skipTestsReason"`

	TestSpecs []any/* CUE closed list */ `json:"testSpecs"`
}

type TaskExecutionResult struct {
	Gates TaskGates `json:"gates"`

	Files TaskFiles `json:"files,omitempty"`

	FilesModified []string `json:"filesModified,omitempty"`

	FilesCreated []string `json:"filesCreated,omitempty"`

	FilesDeleted []string `json:"filesDeleted,omitempty"`

	ScopeAdjustments []any/* CUE closed list */ `json:"scopeAdjustments"`

	Agents []any/* CUE closed list */ `json:"agents"`

	InvariantsChecked []any/* CUE closed list */ `json:"invariantsChecked"`

	FileEditsSummary map[string]struct {
		Edits int64 `json:"edits,omitempty"`

		Details []string `json:"details,omitempty"`
	} `json:"fileEditsSummary,omitempty"`

	TestsRan TestsRan `json:"testsRan,omitempty"`

	NextSteps string `json:"nextSteps"`
}

type TaskGates struct {
	Baseline GateRow `json:"baseline"`

	PostChange GateRow `json:"postChange"`

	Regression []any/* CUE closed list */ `json:"regression"`
}

type GateRow map[string]any /* CUE top */

type TaskFiles struct {
	Created []any/* CUE closed list */ `json:"created"`

	Modified []any/* CUE closed list */ `json:"modified"`

	Deleted []any/* CUE closed list */ `json:"deleted"`
}

type TestsRan struct {
	PreChange struct {
		TestCount string `json:"testCount,omitempty"`

		Duration string `json:"duration,omitempty"`

		Details string `json:"details,omitempty"`
	} `json:"preChange,omitempty"`

	PostChange struct {
		TestCount string `json:"testCount,omitempty"`

		Duration string `json:"duration,omitempty"`

		Details string `json:"details,omitempty"`
	} `json:"postChange,omitempty"`
}

type Invariant struct {
	Rule string `json:"rule"`

	Source string `json:"source,omitempty"`
}

type SkillFound struct {
	Domain string `json:"domain"`

	Skill string `json:"skill"`

	Relevance string `json:"relevance"`
}

type TestSpec struct {
	TestId string `json:"testId"`

	File string `json:"file"`

	Type string `json:"type"`

	Description string `json:"description"`

	CoverageTarget string `json:"coverageTarget,omitempty"`
}

type RegressionRow struct {
	File string `json:"file"`

	Test string `json:"test"`

	Result string `json:"result"`
}

type TaskAgent struct {
	Role string `json:"role"`

	Skill string `json:"skill"`

	Model any/* CUE disjunction: (null|string) */ `json:"model"`

	Status string `json:"status"`

	StartedAt string `json:"startedAt,omitempty"`

	CompletedAt string `json:"completedAt,omitempty"`

	SkillsLoaded []string `json:"skillsLoaded,omitempty"`

	Notes string `json:"notes,omitempty"`
}

type InvariantCheck struct {
	Rule string `json:"rule"`

	Source string `json:"source"`

	Status string `json:"status"`

	Note string `json:"note,omitempty"`
}

type ScopeAdjustment struct {
	Kind string `json:"kind"`

	Adjustment string `json:"adjustment"`

	Reason string `json:"reason"`

	Resolution string `json:"resolution"`

	Owner string `json:"owner"`

	LoggedAsWarning bool `json:"loggedAsWarning,omitempty"`
}

// =============================================================
// BRAINSTORMING
// =============================================================
type BrainstormingStep map[string]any /* CUE top */

type Brainstorming struct {
	QuestionsAsked int64 `json:"questionsAsked"`

	ResearchRoundRun bool `json:"researchRoundRun"`

	ResearchAgents int64 `json:"researchAgents"`

	Dimensions BrainstormDimensions `json:"dimensions"`

	ResearchFindings []any/* CUE closed list */ `json:"researchFindings"`

	Assumptions []any/* CUE closed list */ `json:"assumptions"`

	OpenRisks []any/* CUE closed list */ `json:"openRisks"`

	Decision any/* CUE disjunction: (null|struct) */ `json:"decision"`
}

type BrainstormDimensions struct {
	PrimaryUser string `json:"primaryUser"`

	JobToBeDone string `json:"jobToBeDone"`

	SuccessSignal string `json:"successSignal"`

	InScope []string `json:"inScope"`

	OutOfScope []string `json:"outOfScope"`

	RepoSurface []any/* CUE closed list */ `json:"repoSurface"`

	TechConstraints []any/* CUE closed list */ `json:"techConstraints"`

	FailureModes []any/* CUE closed list */ `json:"failureModes"`

	AcceptanceCriteria []any/* CUE closed list */ `json:"acceptanceCriteria"`

	Dependencies []any/* CUE closed list */ `json:"dependencies"`

	OpenQuestions []any/* CUE closed list */ `json:"openQuestions"`
}

type BrainstormDecision struct {
	Chosen string `json:"chosen"`

	Rationale string `json:"rationale"`

	AlternativesConsidered []any/* CUE closed list */ `json:"alternativesConsidered"`
}

type BrainstormAlternative struct {
	Name string `json:"name"`

	Reason_rejected string `json:"reason-rejected"`
}

type ResearchFinding struct {
	Question string `json:"question"`

	Answer string `json:"answer"`

	Confidence string `json:"confidence"`

	Sources []any/* CUE closed list */ `json:"sources"`
}

// =============================================================
// CODE_REVIEW
// =============================================================
type CodeReviewStep map[string]any /* CUE top */

type CodeReview struct {
	AgentTeamsEnabled bool `json:"agentTeamsEnabled,omitempty"`

	DispatchMode string `json:"dispatchMode"`

	ReviewTier string `json:"reviewTier"`

	TokenCostEstimate int64 `json:"tokenCostEstimate,omitempty"`

	MandatoryMembers []string `json:"mandatoryMembers"`

	RecommendedMembers []any/* CUE closed list */ `json:"recommendedMembers"`

	CustomMembers []any/* CUE closed list */ `json:"customMembers"`

	Consolidator CodeReviewConsolidator `json:"consolidator,omitempty"`

	Baseline CodeReviewBaseline `json:"baseline,omitempty"`

	SeverityCounts SeverityCounts `json:"severityCounts,omitempty"`

	CyclomaticAudit CyclomaticAudit `json:"cyclomaticAudit,omitempty"`

	DuplicationFindings []any/* CUE closed list */ `json:"duplicationFindings"`

	RegressionRun any/* CUE disjunction: (null|struct) */ `json:"regressionRun"`

	Findings []any/* CUE closed list */ `json:"findings"`
}

type CodeReviewConsolidator struct {
	Mode string `json:"mode"`

	Reason string `json:"reason,omitempty"`
}

type CodeReviewBaseline struct {
	Source string `json:"source"`

	ReusedGates []any/* CUE closed list */ `json:"reusedGates"`

	FreshGates []any/* CUE closed list */ `json:"freshGates"`

	Duration string `json:"duration,omitempty"`
}

type SeverityCounts struct {
	High int64 `json:"high"`

	Medium int64 `json:"medium"`

	Low int64 `json:"low"`
}

type CyclomaticAudit struct {
	ConductedBy string `json:"conductedBy"`

	Files []any/* CUE closed list */ `json:"files"`
}

type CyclomaticFile struct {
	File string `json:"file"`

	MaxComplexity int64 `json:"maxComplexity"`

	Threshold int64 `json:"threshold"`

	Verdict string `json:"verdict"`
}

type DuplicationFinding struct {
	Pattern string `json:"pattern"`

	Files []string `json:"files"`

	SuggestedExtraction string `json:"suggestedExtraction"`
}

type RegressionRun struct {
	Tool string `json:"tool"`

	Scope string `json:"scope"`

	Command string `json:"command"`

	CommandSource string `json:"commandSource"`

	ExecutionDepth string `json:"executionDepth"`

	FilesInRadius int64 `json:"filesInRadius"`

	TestFilesExecuted int64 `json:"testFilesExecuted"`

	ExitCode int64 `json:"exitCode"`

	Passed int64 `json:"passed"`

	Failed int64 `json:"failed"`

	SkippedTests int64 `json:"skippedTests"`

	Duration string `json:"duration,omitempty"`

	Skipped bool `json:"skipped"`

	SkipReason any/* CUE disjunction: (null|string) */ `json:"skipReason"`

	Summary string `json:"summary"`

	Failures []any/* CUE closed list */ `json:"failures"`
}

type RegressionFailure struct {
	TestFile string `json:"testFile"`

	TestName string `json:"testName"`

	Error string `json:"error"`
}

type Finding struct {
	Id string `json:"id"`

	Domain string `json:"domain"`

	Severity string `json:"severity"`

	Category string `json:"category"`

	File string `json:"file"`

	Line int64 `json:"line,omitempty"`

	Description string `json:"description"`

	SuggestedFix string `json:"suggestedFix"`

	AssignedSkill string `json:"assignedSkill"`

	Status string `json:"status"`
}

// =============================================================
// RECEIVING_CODE_REVIEW
// =============================================================
type ReceivingCodeReviewStep map[string]any /* CUE top */

type ReceivingCodeReview struct {
	Iteration int64 `json:"iteration"`

	Summary ReceivingSummary `json:"summary"`

	Dispatches []any/* CUE closed list */ `json:"dispatches"`

	Unrecovered []any/* CUE closed list */ `json:"unrecovered"`

	Notes string `json:"notes"`
}

type ReceivingSummary struct {
	Total int64 `json:"total"`

	Fixed int64 `json:"fixed"`

	Unrecovered int64 `json:"unrecovered"`
}

type ReceivingDispatch struct {
	FindingId string `json:"findingId"`

	Iteration int64 `json:"iteration"`

	Reason string `json:"reason"`

	Role string `json:"role"`

	Skill string `json:"skill"`

	Model string `json:"model"`

	Status string `json:"status"`

	FilesChanged []any/* CUE closed list */ `json:"filesChanged"`

	GatesPostFix struct {
		Lint string `json:"lint,omitempty"`

		Typecheck string `json:"typecheck,omitempty"`

		Tests string `json:"tests,omitempty"`
	} `json:"gatesPostFix,omitempty"`

	ResearchBundle any/* CUE disjunction: (null|string) */ `json:"researchBundle"`

	FailureTrace any/* CUE disjunction: (null|string) */ `json:"failureTrace"`

	StartedAt string `json:"startedAt"`

	CompletedAt string `json:"completedAt"`
}

type UnrecoveredFinding struct {
	FindingId string `json:"findingId"`

	Severity string `json:"severity"`

	LastTrace string `json:"lastTrace"`

	TotalIterations int64 `json:"totalIterations"`

	ModelsTried []string `json:"modelsTried"`

	ResearchPassesRun int64 `json:"researchPassesRun"`

	LoggedToTechDebt any/* CUE disjunction: (null|string) */ `json:"loggedToTechDebt"`
}

// =============================================================
// WRITE_TESTS
// =============================================================
type WriteTestsStep map[string]any /* CUE top */

type WriteTests struct {
	Skipped bool `json:"skipped"`

	SkipReason any/* CUE disjunction: (null|string) */ `json:"skipReason"`

	Runner any/* CUE disjunction: (null|string) */ `json:"runner"`

	FilesAuthored []any/* CUE closed list */ `json:"filesAuthored"`

	GreenTests GreenTests `json:"greenTests,omitempty"`

	MutationTesting MutationTesting `json:"mutationTesting,omitempty"`

	Notes string `json:"notes"`
}

type GreenTests struct {
	Added int64 `json:"added"`

	Augmented int64 `json:"augmented"`

	Duration string `json:"duration,omitempty"`
}

type MutationTesting struct {
	Ran bool `json:"ran"`

	Tool any/* CUE disjunction: (null|string) */ `json:"tool"`

	Score int64 `json:"score"`

	Target int64 `json:"target"`

	Survivors []any/* CUE closed list */ `json:"survivors"`

	CoverageGap any/* CUE disjunction: (null|struct) */ `json:"coverageGap"`
}

type MutationSurvivor struct {
	File string `json:"file"`

	Line int64 `json:"line"`

	Mutator string `json:"mutator"`

	KilledByNewTest bool `json:"killedByNewTest"`

	AddedTestFile string `json:"addedTestFile"`
}

type MutationCoverageGap struct {
	Reason string `json:"reason"`

	UncoveredFiles []string `json:"uncoveredFiles"`

	Remediation string `json:"remediation"`
}

// =============================================================
// UPDATE_DOCS
// =============================================================
type UpdateDocsStep map[string]any /* CUE top */

type UpdateDocs struct {
	DocsMentioning []any/* CUE closed list */ `json:"docsMentioning"`

	AnchorDocsAlwaysIncluded []any/* CUE closed list */ `json:"anchorDocsAlwaysIncluded"`

	Patches []any/* CUE closed list */ `json:"patches"`

	TwoPassRun TwoPassRun `json:"twoPassRun"`
}

type TwoPassRun struct {
	DirectRef bool `json:"directRef"`

	ConceptLevel bool `json:"conceptLevel"`

	MentionsPass bool `json:"mentionsPass"`

	MentionsFallbackUsed bool `json:"mentionsFallbackUsed"`

	MentionsResultEmpty any/* CUE disjunction: (null|string) */ `json:"mentionsResultEmpty"`

	MentionsFallback any/* CUE disjunction: (null|string) */ `json:"mentionsFallback"`
}

type DocMention struct {
	SourceFile string `json:"sourceFile"`

	MentionedBy []struct {
		Doc string `json:"doc"`

		Confidence float64 `json:"confidence"`
	} `json:"mentionedBy"`
}

type AnchorDoc struct {
	Doc string `json:"doc"`

	Source string `json:"source"`

	Disposition string `json:"disposition"`
}

type DocPatch struct {
	Doc string `json:"doc"`

	Reason string `json:"reason"`

	LinesChanged int64 `json:"linesChanged"`

	Verdict string `json:"verdict"`

	Notes string `json:"notes,omitempty"`
}

// =============================================================
// FEATURE_ACCEPTANCE
// =============================================================
type FeatureAcceptanceStep map[string]any /* CUE top */

type FeatureAcceptance struct {
	Mode string `json:"mode"`

	ModeNote string `json:"modeNote"`

	AcceptanceCriteria []FAcceptanceCriterion `json:"acceptanceCriteria"`

	NfrVerifications []any/* CUE closed list */ `json:"nfrVerifications"`

	SuccessMetrics []any/* CUE closed list */ `json:"successMetrics"`

	AcRelaxations []any/* CUE closed list */ `json:"acRelaxations"`

	OperatorActionsRequested []any/* CUE closed list */ `json:"operatorActionsRequested"`

	Verdict string `json:"verdict,omitempty"`

	ExecutionRequiredProbe bool `json:"executionRequiredProbe"`

	LiveVerificationAttempt bool `json:"liveVerificationAttempt"`
}

type FAcceptanceCriterion struct {
	Id string `json:"id"`

	Status string `json:"status"`

	Evidence string `json:"evidence"`

	Method string `json:"method"`

	Rationale string `json:"rationale,omitempty"`
}

type FNFR struct {
	Id string `json:"id"`

	Status string `json:"status"`

	CoversAcceptanceSignal string `json:"coversAcceptanceSignal"`

	Evidence string `json:"evidence"`

	Measured string `json:"measured"`

	Target string `json:"target"`
}

type FSuccessMetric struct {
	Id string `json:"id"`

	Measured any/* CUE disjunction: (string|number) */ `json:"measured"`

	Target any/* CUE disjunction: (string|number) */ `json:"target"`

	Status string `json:"status"`
}

type ACRelaxation struct {
	AcId string `json:"acId"`

	OriginalTarget string `json:"originalTarget"`

	RelaxedTarget string `json:"relaxedTarget"`

	Rationale string `json:"rationale"`

	Source string `json:"source"`

	At string `json:"at"`
}

type OperatorAction struct {
	Ac any/* CUE disjunction: (null|string) */ `json:"ac"`

	Kind string `json:"kind"`

	Description string `json:"description"`

	At string `json:"at"`

	Resolved bool `json:"resolved"`

	Resolution any/* CUE disjunction: (null|string) */ `json:"resolution"`
}

// =============================================================
// COMMIT
// =============================================================
type CommitStep map[string]any /* CUE top */

type CommitDescriptor struct {
	Sha string `json:"sha,omitempty"`

	ConventionalType string `json:"conventionalType"`

	Scope string `json:"scope"`

	Subject string `json:"subject"`

	Body string `json:"body"`

	Trailers []any/* CUE closed list */ `json:"trailers"`

	PrePushAuditsRun []any/* CUE closed list */ `json:"prePushAuditsRun"`

	PushAttempts []any/* CUE closed list */ `json:"pushAttempts"`

	PrePushAudits []any/* CUE closed list */ `json:"prePushAudits"`
}

type PushAttempt struct {
	Sha string `json:"sha"`

	AttemptedAt string `json:"attemptedAt"`

	LefthookBypassed bool `json:"lefthookBypassed"`

	NoVerifyPassed bool `json:"noVerifyPassed"`

	AmendUsed bool `json:"amendUsed"`

	BypassedAudits []any/* CUE closed list */ `json:"bypassedAudits"`

	BypassReason any/* CUE disjunction: (null|string) */ `json:"bypassReason"`

	RetryCount int64 `json:"retryCount"`

	PreviousFailure any/* CUE disjunction: (null|string) */ `json:"previousFailure"`
}

type PrePushAudit struct {
	Name string `json:"name"`

	Source string `json:"source"`

	ExitCode int64 `json:"exitCode"`

	DurationMs int64 `json:"durationMs"`

	Output string `json:"output,omitempty"`
}

// =============================================================
// Step-type discriminator registry — used by codegen + describe-step-type.
// =============================================================
type StepDefinitions struct {
	PRD PRDStep `json:"PRD"`

	TASKS_MANIFEST TasksManifestStep `json:"TASKS_MANIFEST"`

	TASK TaskStep `json:"TASK"`

	BRAINSTORMING BrainstormingStep `json:"BRAINSTORMING"`

	CODE_REVIEW CodeReviewStep `json:"CODE_REVIEW"`

	RECEIVING_CODE_REVIEW ReceivingCodeReviewStep `json:"RECEIVING_CODE_REVIEW"`

	WRITE_TESTS WriteTestsStep `json:"WRITE_TESTS"`

	UPDATE_DOCS UpdateDocsStep `json:"UPDATE_DOCS"`

	FEATURE_ACCEPTANCE FeatureAcceptanceStep `json:"FEATURE_ACCEPTANCE"`

	COMMIT CommitStep `json:"COMMIT"`
}
